---
name: Backport Assistant Runner (for OSS & ENT)

on:
  pull_request_target:
    types:
      - closed
      - labeled

jobs:
  backport-targeted-release-branch:
    if: github.event.pull_request.merged
    runs-on: ubuntu-latest
    container: hashicorpdev/backport-assistant:0.2.5
    steps:
      - name: Backport changes to targeted release branch
        run: |
          backport-assistant backport
        env:
          BACKPORT_LABEL_REGEXP: "backport/(?P<target>\\d+\\.\\d+\\.[+\\w]+)"
          BACKPORT_TARGET_TEMPLATE: "release/{{.target}}"
          BACKPORT_MERGE_COMMIT: true
          GITHUB_TOKEN: ${{ secrets.ELEVATED_GITHUB_TOKEN }}
